MusikPortal/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusikPortal.Models;
using MusicPortal.BLL.DTO;
using MusicPortal.BLL.Interfaces;
using MusicPortal.BLL.Infrastructure;
using System.IO;
using MusicPortal.BLL.Services;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using MusicPortal.Filters;

namespace MusikPortal.Controllers
{
    [Culture]
    public class AdminController : Controller
    {
        IWebHostEnvironment _appEnvironment;
        private readonly ISongService songService;
        private readonly IArtistService artistService;
        private readonly IStyleService styleService;
        private readonly IUserService userService;
        private readonly ISaltService saltService;
        public AdminController(ISongService s, IArtistService a, IStyleService st, IUserService u, ISaltService t, IWebHostEnvironment appEnvironment)
        {
            songService = s;
            artistService = a;
            styleService = st;
            userService = u;
            saltService = t;
            _appEnvironment = appEnvironment;
        }
        public async Task<IActionResult> Styles()
        {
            IEnumerable<StyleDTO> s = await styleService.GetAllStyles();
            ViewData["StyleId"] = new SelectList(s, "Id", "Name");
            return PartialView("Styles");
        }
        public async Task<IActionResult> Artists()
        {
            IEnumerable<ArtistDTO> a = await artistService.GetAllArtists();
            ViewData["ArtistId"] = new SelectList(a, "Id", "Name");
            return PartialView("Artists");
        }
        public async Task<IActionResult> EditArtist(int id)
        {
            ArtistDTO a = await artistService.GetArtist(id);
            return PartialView("EditArtist",a);
        }
        public async Task<IActionResult> EditStyle(int id)
        {
            StyleDTO a = await styleService.GetStyle(id);
            return PartialView("EditStyle", a);
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateStyle(StyleDTO s)
        {
            StyleDTO style = new StyleDTO();
            style.Name = s.Name;
            if (ModelState.IsValid)
            {
                try
                {
                    await styleService.AddStyle(style);                
                    return RedirectToAction("Index", "Home");                   
                }
                catch
                {
                    await putStyles(); 
                    return View("Styles", s);
                }

            }
            await putStyles();
            return View("Styles", s);
        }
        [HttpPost]
        public async Task<IActionResult> CreateArtist(string Name, IFormFile p)
        {
            if (p != null)
            {
                string str = p.FileName.Replace(" ", "_");
                string str1 = str.Replace("-", "_");
                // Путь к папке Files
                string path = "/Photos/" + str1; // имя файла

                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await p.CopyToAsync(fileStream); // копируем файл в поток
                }
                ArtistDTO art = new ArtistDTO();
                art.Name = Name;
                art.photo = path;
               
                    try
                    {
                        await artistService.AddArtist(art);                    
                        return Json(true);
                    }
                    catch
                    {
                        await putArtists();
                    return Json(false);
                }               
            }
            ModelState.AddModelError("", "enter the photo");
            await putArtists();
            return Json(false);
        }
        [HttpGet]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteStyle(int id)
        {                  
                try
                {
                /* await styleService.DeleteStyle(s.Id);
                 return RedirectToAction("Index", "Home");*/
                StyleDTO a = await styleService.GetStyle(id);
                return PartialView(a);
            }
                catch
                {
                await putStyles();              
                return Json(false);
            }           
        }
        [HttpGet]
        public async Task<IActionResult> DeleteArtist(int id)
        {
            try
            {
                ArtistDTO a = await artistService.GetArtist(id);
                return PartialView(a);
            }
            catch
            {
                await putArtists();
                return Json(false);
            }
        }
        [HttpPost]      
        public async Task<IActionResult> ConfirmDeleteArtist(int id)
        {
            try
            {
                await artistService.DeleteArtist(id);
                return Json(true);
            }
            catch
            {            
                return Json(false);
            }
        }
        [HttpPost]
        public async Task<IActionResult> ConfirmDeleteStyle(int id)
        {
            try
            {
                await styleService.DeleteStyle(id);
                return Json(true);
            }
            catch
            {
                return Json(false);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CancelDeleteArtist()
        {
            await putArtists();
            return View("Artists");
        }
        [HttpPost]
      //  [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditStyle(StyleDTO s)
        {
                if (ModelState.IsValid)
                {
                    try
                    {
                     await styleService.UpdateStyle(s.Id,s.Name);
                     return Json(true);

                }
                    catch
                    {
                        await putStyles();
                    // return View("Styles");
                    return Json(false);
                }

                }
            await putStyles();       
            return Json(false);
        }
        [HttpPost]
        public async Task<IActionResult> EditArtist(ArtistDTO s, IFormFile? p)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (p != null)
                    {
                        string str = p.FileName.Replace(" ", "_");
                        string str1 = str.Replace("-", "_");
                        // Путь к папке Files
                        string path = "/Photos/" +str1; // имя файла

                        using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                        {
                            await p.CopyToAsync(fileStream); // копируем файл в поток
                        }
                        await artistService.UpdateArtist(s.Id, s.Name, path);
                        return Json(true);
                    }
                    else
                        await artistService.UpdateArtist(s.Id, s.Name,s.photo);
                    return Json(true);
                }
                catch
                {
                    return Json(false);
                }

            }
            return Json(false);
        }
        public async Task putStyles()
        {
            IEnumerable<StyleDTO> s = await styleService.GetAllStyles();
            ViewData["StyleId"] = new SelectList(s, "Id", "Name");          
        }
        public async Task putArtists()
        {
            IEnumerable<ArtistDTO> a = await artistService.GetAllArtists();
            ViewData["ArtistId"] = new SelectList(a, "Id", "Name");
        }
        public async Task putUsers()
        {
            IEnumerable<UserDTO> s = await userService.GetUsers(HttpContext.Session.GetString("login"));
            ViewBag.Users = s;
        }
        public async Task<IActionResult> Users()
        {
            IEnumerable<UserDTO> s = await userService.GetUsers(HttpContext.Session.GetString("login"));
            return PartialView(s);
        }
        [HttpPost]
        public async Task<IActionResult> EditUser( int id,int level)//[Bind("Id,Name,email,Age,Level")]  UserDTO u)  //UserDTO u)
        {
           
            try
            {
                UserDTO u = await userService.GetUser(id);
                if (u != null)
                {
                    await userService.UpdateUser(id, level);
                    IEnumerable<UserDTO> s1 = await userService.GetUsers(HttpContext.Session.GetString("login"));
                    return Json(true);
                }
                else
                    return Json(false);
            }
            catch
            {               
                return Json(false);
            }

        }
        [HttpGet]
        public async Task<IActionResult> GetUser(int id)
        {
            try
            {
                UserDTO u= await userService.GetUser(id);
                if (u != null)
                {
                    return PartialView("ChangeUser", u);
                }
                else
                    return Json(false);
            }
            catch
            {
                return Json(false);
            }
        }

           
        public async Task<IActionResult> DeleteSong(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            SongDTO s = await songService.GetSong(id);
            if (s == null)
            {
                return NotFound();
            }

            return PartialView(s);
        }

MusikPortal/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using MusikPortal.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using MusicPortal.BLL.Interfaces;
using MusicPortal.BLL.DTO;
using MusicPortal.BLL.Services;
using MusicPortal.Filters;


namespace MusikPortal.Controllers
{
    [Culture]
    public class SongController : Controller
    {
        IWebHostEnvironment _appEnvironment;
        private readonly ISongService songService;
        private readonly IArtistService artistService;
        private readonly IStyleService styleService;
        public SongController(ISongService s, IArtistService a, IStyleService st, IWebHostEnvironment appEnvironment)
        {
            songService = s;
            artistService = a;
            styleService = st;
            _appEnvironment = appEnvironment;
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await putStylesArtists();
            //return View("AddSong");
            return PartialView("AddSong");
        }
        [HttpPost]
       // [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( AddSong song, IFormFile file)
        {            
            if (file == null)
                ModelState.AddModelError("", "put the file");
            DateTime today = DateTime.Today;
            int currentYear = today.Year;
            try
            {
                if (Convert.ToInt32(song.Year) < 0 || Convert.ToInt32(song.Year) > currentYear)
                    ModelState.AddModelError("", "uncorrectly year");
            }
            catch { ModelState.AddModelError("", "uncorrectly year"); }
            if (file != null)
            {
                string str= file.FileName.Replace(" ", "_");
                string str1 = str.Replace("-", "_");
                // Путь к папке Files
                string path = "/MusicFiles/" + str1; // имя файла

                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream); // копируем файл в поток
                }
                SongDTO s = new();
                StyleDTO sStyle = await styleService.GetStyle(song.StyleId);
                ArtistDTO aArtist = await artistService.GetArtist(song.ArtistId);
                s.Name = song.Name;
                s.style =sStyle.Name;
                s.styleId = sStyle.Id;
                s.artist = aArtist.Name;
                s.artistId = aArtist.Id;
                s.artistPhoto = aArtist.photo;
                s.Year = song.Year;
                s.text = song.text;
                s.Album=song.Album; 
                s.file = path;
                if (ModelState.IsValid)
                {
                    try
                    {
                        await songService.AddSong(s);                       
                        await songService.AddSongToArtist(song.ArtistId, s);
                         return PartialView("Success");
                       // return Json("success");
                    }
                    catch
                    {
                        await putStylesArtists();
                        return PartialView("AddSong", song);
                    }
                }
                else
                {
                    await putStylesArtists();
                    return PartialView("AddSong", song);
                }
            }
            await putStylesArtists();
            return PartialView("AddSong", song);
        }
        public async Task putStylesArtists()
        {
            IEnumerable<StyleDTO> s = await styleService.GetAllStyles();
            IEnumerable<ArtistDTO> a = await artistService.GetAllArtists();
            ViewData["StyleId"] = new SelectList(s, "Id", "Name");
            ViewData["ArtistId"] = new SelectList(a, "Id", "Name");
        }
       
    }
}

MusikPortal/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Resources.Resource.MusicPortal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MusicPortal.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/base/jquery-ui.css" />
    @* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" /> 
    <script src="~/js/site.js" ></script>*@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> 
</head>
<body>
    <header>
        <div style=" background-color:saddlebrown;" class="center">
            <h1 class="c20">@Resources.Resource.MusicPortal </h1>
            @using (Html.BeginForm("ChangeCulture", "Home"))
            {
                <div class="m2"> 
                <select name="lang" class="form-control i">
                    <option value="ru">Русский</option>
                    <option value="en">English</option>
                    <option value="uk">Українська</option>
                    <option value="de">Deutsch</option>
                    <option value="fr">Français</option>
                </select>
                    <input type="submit" name="submit" value="@Resources.Resource.ChooseLang" class="btn btn-default c20">
                </div>
            }
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-1" >
            <div class="container-fluid" style="background-color:brown">
                
                <a href="javascript:void(0)" class="navbar-brand card2 c23 btn-music">@Resources.Resource.AllSongs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @using (Html.BeginForm("Find", "Home", FormMethod.Get))
                {
                    <div style="display:flex">
                        <input type="text" id="str" name="str" />
                        <a href="javascript:void(0)" class="card2 btn-find">@Resources.Resource.Find</a>&nbsp;
                    </div>
                }
                
                   
                                           
                    <div class="navbar-collapse collapse d-sm-inline-flex c c21">
                            
                                <div class=" m1">
                        <a asp-action="Create" id="addSong" asp-controller="Song" class="card2 non m createSong" data_dialog_title="Addition Song">@Resources.Resource.AddSong</a>&nbsp;&nbsp;&nbsp;
                                </div>
                            
                        @using (Html.BeginForm("Styles", "Admin", FormMethod.Get))
                        {
                        <div >
                            <a href="javascript:void(0)" class="card2 non" id="genres">@Resources.Resource.Genres</a>&nbsp;
                             </div>
                        }
                        @using (Html.BeginForm("Artists", "Admin", FormMethod.Get))
                        {
                        <div class=" m1">
                            @*<input type="submit" id="artists" class="non" value="Artists" />&nbsp;*@
                            <a href="javascript:void(0)" class="card2 non" id="artists">@Resources.Resource.Artists</a>&nbsp;
                            </div>
                        }                     
                        @using (Html.BeginForm("Users", "Admin", FormMethod.Get))
                        {
                        <div >
                            <a href="javascript:void(0)" class="card2 non" id="users">@Resources.Resource.Users</a>&nbsp;
                            </div>
                        }
                    </div>


                <div class="c20 " id="wait" style="display:none;">waiting for confirm registration&nbsp;&nbsp;&nbsp;</div>

                @using (Html.BeginForm("Logout", "Login", FormMethod.Get))
                {                  
                        <div style="display:flex; justify-content:end; width:400px;">
                           <div class="c c1 c20 non" id="wellcome" >

                            &nbsp;&nbsp;&nbsp;&nbsp;@Resources.Resource.Welcome, &nbsp; <span id="wellcomeTo"></span>&nbsp;&nbsp;

                        </div>                       
                        </div>
                 }
                <a href="javascript:void(0)" class="nav-link text-dark card2 btn-Logout non" id="logout">@Resources.Resource.LogOut</a>
                <ul class="navbar-nav flex-grow-1 c c1 " id="enter">
                        <li class="nav-item">
                        <a href="javascript:void(0)" class="nav-link text-dark card2 btn-Login">@Resources.Resource.Login</a>
                        </li>
                        <li class="nav-item">
                        <a href="javascript:void(0)" class="nav-link text-dark card2 btn-Reg">@Resources.Resource.Registration</a>
                        </li>
                    </ul>
               

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container c20">
            &copy; 2023 - MusicPortal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*<script src="~/js/jquery-ui-1.12.1.js"> </script>*@
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script> 
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>